### ISSUE TITLE
JUnit XML empty while using with monocart network report

### ISSUE THREAD

**Issue by bogdan-sweap** [Xray-App/playwright-junit-reporter#13]
While using the JUnit reporter with monocart and network report, the XML file is empty since an exception is thrown produced by:
the line `throw new console.warn(...)`.

Exception:
`Error in reporter TypeError: console.warn is not a constructor

    at ContentTypeMapper.getFileExtenion (ui-tests/node_modules/@xray-app/playwright-junit-reporter/dist/contentType.mapper.js:19:23)
    
    at XrayJUnitReporter._addTestCase (ui-tests/node_modules/@xray-app/playwright-junit-reporter/dist/index.js:203:160)
    
    at ui-tests/node_modules/@xray-app/playwright-junit-reporter/dist/index.js:109:18
    
    at Array.forEach (<anonymous>)
`
Configuration of Playwright reporters:
`const xrayOptions = {

    embedAnnotationsAsProperties: true,
    
    textContentAnnotations: ['test_description'],
    
    embedAttachmentsAsProperty: 'testrun_evidence',
    
    outputFile: testReportJUnit
    
  };

export default defineConfig({
...
  reporter: [
    ['line'],
    
    ['@xray-app/playwright-junit-reporter', xrayOptions],
    
    ['monocart-reporter', {
    
      reportTitle: "UI Test Report",
      
      outputFile: './monocart.html',
      
      trace: true,
      
      includeTrace: true,
      
      network: true
      
    }]
    
]
`

**Comment by bitcoder** [comment]
closed by PR  #14
