### ISSUE TITLE
Can we ignore set up and teardown in the report.xml

### ISSUE THREAD

**Issue by LinhDo-LGG** [Xray-App/playwright-junit-reporter#7]
Because setup and teardown in Playwright are tests, when uploading the report to Xray, it will create 2 test cases for setup and teardown. Is there any way to run these setups but exclude them when generating the report.xml file?

**Comment by LinhDo-LGG** [comment]
Resolve the issue with below steps:
1. Read the xml file
2. Convert to js object
3. Loop through test suites
4. Remove setup and teardown test suites
5. Convert the object back to xml string
6. Call the API

**Comment by bitcoder** [comment]
If you were referring to global setup/teardown, there's currently no specific handling of it

**Comment by bitcoder** [comment]
Going to close this on the upcoming days for lack of feedback
